### ISSUE TITLE
Encountering a weird edge case where exposures are ignored? 

### ISSUE THREAD

**Issue by kgaidis** [statsig-io/ios-sdk#16]
Edit: in comments below I maybe found the problem, and maybe it's expected, but it doesn't feel intuitive?

---

Hi there!

For context, been using Statsig for a bit on iOS, but recently ran into a very confusing scenario (I've never had this problem before):

1. ...I've logged \~800 exposures
2. ...Statsig UI says I've logged \~19

I tried to examine my code but so far no luck in identifying a problem. Then I realized I maybe am doing something relatively unique and that could be a trigger for issues?

This is my recap of the flow on how I am utilizing Statsig for this scenario:

1. I have a Statsig feature gate that's set to use a stable ID via Statsig website GUI
2. App starts for the first time for a newly downloaded user
3. `Statsig.start` gets called and the app waits
4. After start (which could have error-ed due to timeout or else), app calls `Statsig.getFeatureGateWithExposureLoggingDisabled("gate_here")` (note: no exposure logged)
5. User logs in...and note that everything from here happens very quickly together
6. ⚠️ `Statsig.updateUser(StatsigUser(userID: userId))` gets called
7. ⚠️ `Statsig.manuallyLogGateExposure("gate_here")` gets called

⚠️ Could this combination of stable id, and calling `Statsig.updateUser` AND calling `Statsig.manuallyLogGateExposure` mess something about Statsig? (this happens quite quickly together but the order is correct: updateUser first, then manuallyLogGateExposure)

The update user does have some code around removing exposures:

[https://github.com/statsig-io/ios-sdk/blob/345133bb464a4b10916e1cc743c3784ac1c4e159/Sources/Statsig/StatsigClient.swift#L122-L125](https://github.com/statsig-io/ios-sdk/blob/345133bb464a4b10916e1cc743c3784ac1c4e159/Sources/Statsig/StatsigClient.swift#L122-L125)

---

*(If you wonder why I chose a stable id when I'm logging exposure after getting the user...I was actually afraid that Statsig might not handle this scenario of logging exposures/gate while* `updateUser` is called in such close succession...it felt safer to choose a stable id because I didn't think anything should go wrong with that...I've had some other previous weird experiences where metrics felt off when running experiments early in the app flow)

---

Statsig version for iOS (I only use iOS): 1.40.1

---

Stable ID set:

![Screenshot 2024-06-05 at 9 01 26 PM](https://uploads.linear.app/f1edcc2d-7774-452d-a5eb-36a8c38fbe82/e2203666-dd0c-434e-a660-6e585f7748fa/1c7d1c46-6f57-48c2-be31-499d59c92354?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YxZWRjYzJkLTc3NzQtNDUyZC1hNWViLTM2YThjMzhmYmU4Mi9lMjIwMzY2Ni1kZDBjLTQzNGUtYTY2MC02ZTU4NWY3NzQ4ZmEvMWM3ZDFjNDYtNmY1Ny00OGMyLWJlMzEtNDk5ZDU5YzkyMzU0IiwiaWF0IjoxNzE3NjkyNDI4LCJleHAiOjMzMjg4MjUyNDI4fQ.2tUNOK0_BZlMeAUK5SS41Wr4_TGPZQTpOjsUi1rI1QI)

Here are all the exposures I see:

![Screenshot 2024-06-05 at 9 02 10 PM](https://uploads.linear.app/f1edcc2d-7774-452d-a5eb-36a8c38fbe82/b9c5c906-6ee6-4532-8ae1-1c5d28cb47d5/f3c8b995-cead-4f4f-b7a0-cf7060327e09?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YxZWRjYzJkLTc3NzQtNDUyZC1hNWViLTM2YThjMzhmYmU4Mi9iOWM1YzkwNi02ZWU2LTQ1MzItOGFlMS0xYzVkMjhjYjQ3ZDUvZjNjOGI5OTUtY2VhZC00ZjRmLWI3YTAtY2Y3MDYwMzI3ZTA5IiwiaWF0IjoxNzE3NjkyNDI4LCJleHAiOjMzMjg4MjUyNDI4fQ.DXX69-DNmwQBdQ2qiV-5a5hU78TcW4IDNbmHHrDZvZU)

Here is what my analytics see for the `Statsig.getFeatureGateWithExposureLoggingDisabled` call (and I know that most of these result in a call to `Statsig.manuallyLogGateExposure("gate_here")`):

![Screenshot 2024-06-05 at 7 20 01 PM](https://uploads.linear.app/f1edcc2d-7774-452d-a5eb-36a8c38fbe82/8710ae35-99b6-4dcf-ab57-2f5ccba49ee0/29ec4854-f566-43bd-b9c8-f4ba8f4ca2a1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YxZWRjYzJkLTc3NzQtNDUyZC1hNWViLTM2YThjMzhmYmU4Mi84NzEwYWUzNS05OWI2LTRkY2YtYWI1Ny0yZjVjY2JhNDllZTAvMjllYzQ4NTQtZjU2Ni00M2JkLWI5YzgtZjRiYThmNGNhMmExIiwiaWF0IjoxNzE3NjkyNDI4LCJleHAiOjMzMjg4MjUyNDI4fQ.aBw6OlZD-q8mviHJpSCp9Es2tZLMu-wvj_ih-dcEO8M "=919x")

The "uninitialized" is NULL is based off this logic (I know its a bit custom haha, but I've used this for other gates without a problem):

```
/// if null, we are assuming the value has not actually been fetched from Statsig
  func isGateEnabledV2(_ gate: String, logExposure: Bool = true) -> Bool? {
    let featureGate = Statsig.getFeatureGateWithExposureLoggingDisabled(gate)
    let didReceiveGate: Bool = {
      switch featureGate.evaluationDetails.reason {
      case .Recognized:
        return true
      case .Unrecognized:
        return false
      case .Sticky:
        return true
      case .LocalOverride:
        return true
      case .none:
        return false // likely null (we don't know..so assume not initialized)
      }
    }()
    if didReceiveGate {
      if logExposure {
        logGateExposure(gate)
      }
      return featureGate.value
    } else {
      return nil
    }
  }
```

**Comment by kgaidis** [comment]
Hmm Statsig returned true for this (which means it was returned successfully???):

`Statsig.getFeatureGateWithExposureLoggingDisabled("enable_onboarding_questions")`

Yet when calling `Statsig.manuallyLogGateExposure("enable_onboarding_questions")` it seems to have returned this:

```
[Statsig]: The feature gate with name enable_onboarding_questions does not exist. Returning false as the default.
```

**Comment by kgaidis** [comment]
It seems like much of my confusion stems from how Statsig clears the gates when calling `Statsig.updateUser`.

It makes sense that Statsig needs to fetch new values for a user. That being said, in this specific case the user is the same, it's just that the "user_id not established yet" until they log in - but rest is "the same." Not sure if there's a way to communicate that to Statsig. 

I am trying to combat this problem by thinking that I can just rely on the idea that my gate uses a "Stable ID" so "it should just work across logins!" but maybe that's just not true?

**Comment by kgaidis** [comment]
I also maybe could have save the statsig gate and use this function instead (instead of a String):

```
    public func manuallyLogExposure(_ gate: FeatureGate) {
        logGateExposureForGate(gate.name, gate: gate, isManualExposure: true)
    }
```

**Comment by daniel-statsig** [comment]
Hey @kgaidis, sorry for the late reply here. 

It sounds like you found the issue, but let me lay it out to keep things clear.

1. Statsig.start (No UserID), values are loaded.
2. Statsig.getFeatureGateWithExposureLoggingDisabled returns values from step 1
3. Statsig.updateUser (With UserID), pervious values are removed and new values are being fetched
4. Statsig.manuallyLogGateExposure re-checks the gate, which the SDK currently has no values for (its in-flight from the update)

To resolve this, you could move the manual exposure to the updateUser callback .

Or, if you want the cache values from the original initialize call to line up (Since its only the userID that changed), you could use the [StatsigOptions.customCacheKey](https://github.com/statsig-io/ios-sdk/blob/main/Sources/Statsig/StatsigOptions.swift#L101) function. This way you could have a custom storage solution for the User. Be careful with this though, as we usually consider UserID+CustomIDs to be the main thing that decides to bust caching
