### ISSUE TITLE
Parameter stores not being saved

### ISSUE THREAD

**Issue by basselalesh** [statsig-io/ios-sdk#19]
Hey! I recently created a Feature Gate and have been trying to add it to an existing Parameter Store. I noticed that after adding the parameter to the store, then modifying it to set it as a Feature Gate, I can hit Save and see the parameter is added. However, when I refresh the page, I see that it's gone. This worked for me last week, so I'm sure it's an easy fix.

This seems to be the case even when adding a new parameter store parameter without connecting it to a feature gate. Refreshing causes what I saved to go away.

Thank you!

**Comment by tore-statsig** [comment]
![Screenshot 2024-08-05 at 2 36 46 PM](https://github.com/user-attachments/assets/590095eb-59b4-4181-a793-452c0076bd30)

Are you saving the changes?  When I save, I am not able to reproduce this.

We can definitely make this more obvious though

**Comment by basselalesh** [comment]
ah I see it now... I was full-screen on my new 34 inch monitor today... my bad!

**Comment by tore-statsig** [comment]
Not your bad - we're figuring out a better way to do this.  We may just change it to save when you complete the update dialog instead. Thanks for the feedback

**Comment by basselalesh** [comment]
yeah that's what it _felt_ like I was doing this time after hitting "Create" on the parameter editor pop-up

**Comment by tore-statsig** [comment]
Okay thanks for confirming.  I think the current pattern is closer to some other flows in the product, so we started this way.  We also will have to add support for reviews eventually, which will add a step to the process. But for now I think we can make that dialog auto save the change
