### ISSUE TITLE
Privacy Manfiest

### ISSUE THREAD

**Issue by sashabaranov** [statsig-io/ios-sdk#7]
From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/):

> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.

Could you please add a privacy manifest for this library?

**Comment by tore-statsig** [comment]
I dont see Statsig, nor any library the statsig SDK depends on in the list that you linked - it sounds like it is not required for using the statsig sdk.

**Comment by tore-statsig** [comment]
Closing per the above - Statsig SDK is not relevant here

**Comment by sashabaranov** [comment]
@tore-statsig this was mostly for future-proofing the library. I imagine at some point in the future they might require this manifest for every library.

**Comment by tore-statsig** [comment]
Reopening as we do need to add this due to usage of UserDefaults

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401

**Comment by tore-statsig** [comment]
Published here https://github.com/statsig-io/ios-sdk/releases/tag/1.39.2
