### ISSUE TITLE
SPM package identifier conflict

### ISSUE THREAD

**Issue by DarkAnGth** [statsig-io/ios-sdk#8]
As xCode SPM using last path component of the package URL as identifier, so, in case of statsig SDK the identifier is `ios-sdk`, which may conflict with other packages, for example with [UXCam](https://github.com/uxcam/ios-sdk/issues/20). 
Not sure when Apple will update the identifier generation - I see there were some [old discussions](https://forums.swift.org/t/urls-as-swift-package-identifiers/43404), but till now it works the same.

I would propose to rename the project to `statsig-ios-sdk`, for example, to avoid conflicts with other packages (https://github.com/statsig-io/statsig-ios-sdk)

**Comment by tore-statsig** [comment]
Thanks for the feedback. At this point we have no plans to change for now, if and when this becomes problematic we can address it
